language: elixir
elixir:
  - 1.6.5
sudo: false # Using faster container based build environment.
script:
  - mix test
  - MIX_ENV=docs mix docs
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
notifications:
  email: false
