language: elixir
elixir:
  - 1.7
sudo: false # Using faster container based build environment.
script:
  - mix test
  - mix docs
after_script:
  - mix deps.get
  - mix inch.report
notifications:
  email: false
