language: elixir
sudo: false # Using faster container based build environment.
script: mix test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
notifications:
  email: false
